# routes pour l'administration
mesclics_admin_posts:
    path: /
    defaults:
        _controller: MesClicsPostBundle:Post:posts

# mesclics_admin_posts_desc:
#     path: _ordre=z-a
#     defaults:
#         _controller: MesClicsPostBundle:Post:posts
#         filter: null
#         sort: 'DESC'

# mesclics_admin_posts_date_creation:
#     path: _tri=date-creation
#     defaults:
#         _controller: MesClicsPostBundle:Post:posts
#         order_by: 'date-creation'
#         sort: 'ASC'

# mesclics_admin_posts_date_creation_desc:
#     path: _tri=date-creation_ordre=z-a
#     defaults:
#         _controller: MesClicsPostBundle:Post:posts
#         order_by: 'date-creation'
#         sort: 'DESC'

# mesclics_admin_posts_title:
#     path: _tri=titres
#     defaults:
#         _controller: MesClicsPostBundle:Post:posts
#         order-by: 'titre'
#         sort: 'ASC'

# mesclics_admin_posts_title_desc:
#     path: _tri=titres_ordre=z-a
#     defaults:
#         _controller: MesClicsPostBundle:Post:posts
#         order-by: 'titre'
#         sort: 'DESC'

# mesclics_admin_posts_date_publication:
#     path: _tri=date-publication-debut
#     defaults:
#         _controller: MesClicsPostBundle:Post:posts
#         order-by: 'date-publication-debut'
#         sort: 'ASC'

# mesclics_admin_posts_date_publication_desc:
#     path: _tri=date-publication-debut_ordre=z-a
#     defaults:
#         _controller: MesClicsPostBundle:Post:posts
#         order-by: 'date-publication-debut'
#         sort: 'DESC'

# mesclics_admin_posts_date_depublication:
#     path: _tri=date-publication-fin
#     defaults:
#         _controller: MesClicsPostBundle:Post:posts
#         order-by: 'date-publication-fin'
#         sort: 'ASC'

# mesclics_admin_posts_date_depublication_desc:
#     path: _tri=date-publication-fin_ordre=z-a
#     defaults:
#         _controller: MesClicsPostBundle:Post:posts
#         order-by: 'date-depublication-fin'
#         sort: 'DESC'

# mesclics_admin_posts_online:
#     path: /en-ligne
#     defaults:
#         _controller: MesClicsPostBundle:Post:onlinePosts

# mesclics_admin_posts_online_desc:
#     path: /en-ligne
#     defaults:
#         _controller: MesClicsPostBundle:Post:onlinePosts
#         sort: 'DESC'

# mesclics_admin_posts_draft:
#     path: /brouillons
#     defaults:
#         _controller: MesClicsPostBundle:Post:draftPosts

mesclics_admin_posts_new:
    path: /new/
    defaults:
        _controller: MesClicsPostBundle:Post:new

mesclics_admin_post:
    path: /{post_id}/
    defaults:
        _controller: MesClicsPostBundle:Post:edit