# routes pour l'administration
#PUBLICATIONS
mesclics_admin_posts:
    path: /publications/
    defaults:
        _controller: MesClicsPostBundle:Post:posts

mesclics_admin_posts_new:
    path: publications/new/
    defaults:
        _controller: MesClicsPostBundle:Post:new
        
mesclics_admin_post_remove:
    path: publications/{post_id}/remove
    defaults:
        _controller: MesClicsPostBundle:Post:remove

mesclics_admin_post_delete:
    path: publication/{post_id}/delete
    defaults:
        _controller: MesClicsPostBundle:Post:delete

mesclics_admin_post_backend_comment:
    path: publications/{post_id}/backup_comment_submission
    defaults:
        _controller: MesClicsPostBundle:BackendComment:create

mesclics_admin_post_backend_comment_update:
    path: publications/{post_id}/backend_comment/{comment_id}/update
    defaults:
        _controller: MesClicsPostBundle:BackendComment:update

mesclics_admin_post_backend_comment_reply:
    path: publications/{post_id}/backup_comment/{comment_id}/reply
    defaults:
        _controller: MesClicsPostBundle:BackendComment:reply

mesclics_admin_post_backend_comment_remove:
    path: publications/{post_id}/backup_comment/{comment_id}/remove
    defaults:
        _controller: MesClicsPostBundle:BackendComment:remove

mesclics_admin_post_backend_comment_delete:
    path: publications/{post_id}/backup_comment/{comment_id}/delete
    defaults:
        _controller: MesClicsPostBundle:BackendComment:delete

mesclics_admin_post_backend_comment_pin:
    path: publications/{post_id}/backup_comment/{comment_id}/pin
    defaults:
        _controller: MesClicsPostBundle:BackendComment:pin
        

mesclics_admin_post:
    path: publications/{post_id}/
    defaults:
        _controller: MesClicsPostBundle:Post:update

        
#COLLECTIONS
mesclics_admin_collections:
    path: collections/
    defaults:
        _controller: MesClicsPostBundle:Collection:collections

mesclics_admin_collections_new:
    path: collections/new/
    defaults:
        _controller: MesClicsPostBundle:Collection:new

mesclics_admin_collection:
    path: collections/{collection_id}/
    defaults:
        _controller: MesClicsPostBundle:Collection:update