# routes pour l'administration
#PUBLICATIONS
mesclics_admin_posts:
    path: /publications/
    defaults:
        _controller: MesClicsPostBundle:Post:posts

mesclics_admin_posts_new:
    path: publications/new/
    defaults:
        _controller: MesClicsPostBundle:Post:new

mesclics_admin_post:
    path: publications/{post_id}/
    defaults:
        _controller: MesClicsPostBundle:Post:edit
        
#COLLECTIONS
mesclics_admin_collections:
    path: collections/
    defaults:
        _controller: MesClicsPostBundle:Collection:collections

mesclics_admin_collections_new:
    path: collections/new/
    defaults:
        _controller: MesClicsPostBundle:Collection:new