<?php

namespace MesClics\PostBundle\Repository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends \Doctrine\ORM\EntityRepository{
    public function getAll(){
        $qb = $this
        ->createQueryBuilder('collection')
        ->orderBy('collection.entity');

        return $qb->getQuery()->getResult();
    }

    public function getPublic(){

    }

    public function getPrivate(){

    }

    public function getForQB($entity){
        $qb = $this
        ->createQueryBuilder('collection')
        ->andWhere('collection.entity = :entity')
            ->setParameter('entity', $entity);
        return $qb;
    }

    public function getFor($entity){
        $qb = $this->getForQB($entity);
        return $qb->getQuery()->getResult();
    }
}
