<?php

namespace MesClics\PostBundle\Repository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends \Doctrine\ORM\EntityRepository{
    public function getAll(){
        $qb = $this
        ->createQueryBuilder('collection')
        ->orderBy('collection.entity');

        return $qb->getQuery()->getResult();
    }

    public function getPublic(){

    }

    public function getPrivate(){

    }

    public function getFor($entity){

    }
}
